import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useTranslation } from "react-i18next"

const Home: NextPage = () => {
    const { t } = useTranslation()

    return (
        <>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="py-5">
                <Link href="/login">{t("pages:title_keys.login")}</Link> <br />
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Voluptatum itaque assumenda accusamus! Non ut eum eos error id,
                enim soluta dolorem modi, quae reprehenderit optio provident.
                Iste consequatur perferendis quam. Non mollitia commodi
                provident fuga nobis, cum vel assumenda vitae libero, harum
                aliquid praesentium consequuntur, esse ipsa. Facilis blanditiis
                magnam, doloremque exercitationem a odit odio qui non, tempore
                ipsum doloribus! Reprehenderit optio pariatur iure accusantium
                omnis quo accusamus, amet quos totam aperiam ipsa dolorem magni,
                nihil ratione veritatis harum dolores corporis! Fugiat
                distinctio molestiae consequuntur reiciendis maxime, voluptates
                voluptatibus assumenda. Repudiandae sint dolor minima, totam
                dolore aperiam suscipit impedit sunt autem earum nostrum
                voluptatem amet? Corrupti numquam voluptate voluptatibus
                voluptatem temporibus ad quas laudantium at iusto inventore
                nulla, cumque repudiandae. Dignissimos autem magnam ab, corrupti
                magni ullam nemo accusamus non repellendus quos placeat? Ducimus
                laborum velit rerum voluptatum blanditiis eligendi est voluptate
                sed incidunt cupiditate nam magnam sapiente, atque corrupti!
                Atque ullam aut perferendis provident earum incidunt, eaque
                accusantium magni sapiente fugit animi vel hic asperiores eos
                placeat quaerat. Quisquam doloribus obcaecati tempora nihil
                expedita, ex est? Ullam, ad voluptas. Quas laudantium totam
                minus reprehenderit voluptatem odit, quidem asperiores eos velit
                harum dolores nemo explicabo obcaecati officia fugit
                necessitatibus reiciendis repellendus. Ea a debitis, dolor
                expedita blanditiis eos ullam? Placeat? Quibusdam doloribus,
                quia eaque tempora quasi odit commodi, id iure ut unde, nihil
                veritatis amet! Ea, alias est. Sequi sit recusandae minima
                asperiores iure necessitatibus pariatur perferendis
                exercitationem ea! Ipsum. Quasi enim dolorum vero, ut id ipsam
                eius velit aut aperiam nam commodi. Temporibus, enim assumenda
                est doloremque officiis et impedit autem repellat, praesentium,
                eaque cupiditate. Odit cupiditate deleniti eius. Quis aspernatur
                pariatur tempore totam reprehenderit illo consequatur, harum
                sit. Nostrum itaque nobis sequi in beatae ducimus facere unde
                velit porro cum quia, inventore cupiditate voluptas. Minima sit
                dolore qui. Dicta quo necessitatibus deserunt vel ea architecto
                quasi? Illum consequatur totam sequi praesentium vel optio
                libero accusantium cumque debitis? A id corrupti repellendus,
                molestias soluta non at dolorum atque itaque. Quibusdam ut
                architecto fuga iusto quae cupiditate illum. Eaque magni
                architecto, dignissimos labore blanditiis commodi, eos minima
                tempore, quasi deserunt inventore? Quos voluptatibus debitis
                vitae molestiae maiores sunt voluptatem ducimus. Veritatis omnis
                sed debitis ratione similique, molestiae quo odit vero
                aspernatur aliquid asperiores, labore ipsam laudantium ipsa
                eligendi exercitationem. Tempore, ab. Cum dolor cumque
                voluptatibus nostrum sapiente perspiciatis ullam beatae. Magnam,
                suscipit consequuntur sunt debitis minus illum inventore
                explicabo expedita harum eum. Adipisci quas reiciendis facere
                dicta, consectetur nostrum quos! Facilis harum fugit hic qui
                praesentium, aut ullam debitis esse. Hic est cupiditate vel
                accusamus illum inventore sed sit laborum nobis voluptatibus!
                Vero qui maxime iusto amet distinctio aspernatur voluptas quia
                deleniti suscipit dicta, commodi dignissimos, repellendus fugiat
                quasi repellat! Est aliquam consequatur illo, aut illum
                architecto, culpa eveniet omnis eligendi officiis sed doloribus
                exercitationem id minus nihil incidunt in provident ipsum velit
                ut placeat quaerat. Suscipit eum quam omnis. Inventore
                consequatur amet similique in id alias ut nesciunt sapiente iure
                delectus dignissimos dolor, odio, aliquam voluptate temporibus.
                Eos, labore dignissimos doloremque odio fugiat sequi suscipit
                nulla voluptatem quos autem. At, a mollitia dolores quae odio
                incidunt ab assumenda quam voluptates! Voluptates ab
                perspiciatis, necessitatibus, ad explicabo ipsum harum fugit
                amet similique porro quam excepturi quisquam veritatis eveniet,
                accusantium sequi. Debitis commodi, quas deleniti labore sunt
                fuga ab, illum cumque, voluptatum quis itaque quisquam. Nostrum
                dolores facere voluptatem reiciendis vitae dolorum voluptate cum
                repudiandae ut nobis corrupti, error molestias atque. Distinctio
                consequuntur beatae cupiditate voluptatibus quidem saepe sunt
                aperiam, laboriosam, aut hic nihil animi rem. Nobis quo maxime
                magni hic soluta, nihil sed numquam doloribus quod, dignissimos
                iusto vitae eos. Veniam repellat consequuntur similique a nulla
                quis rem vero! Cum repellendus ex perferendis consectetur
                molestias minima, dolores laboriosam nemo, ab voluptates,
                obcaecati nulla deleniti? A quis similique quo animi facere!
                Corrupti earum inventore odio architecto veniam sequi
                perspiciatis, minus eveniet sunt sed omnis! Architecto facere
                nam natus, ipsa blanditiis ex maxime eveniet expedita laborum.
                Saepe laudantium eos sequi dolores reiciendis! Sapiente magni,
                fugit sint eius, modi eaque corrupti vel reiciendis, dolorum
                ipsum quisquam debitis laborum labore iste nisi exercitationem
                nihil unde? Quos animi cupiditate esse corporis ex. Soluta, ut
                magni! Quibusdam perferendis aliquid suscipit a, quae repellat
                porro, sit ex nemo mollitia veritatis quasi repudiandae voluptas
                laborum ducimus exercitationem labore. Nemo, laudantium fugit
                delectus tempora laborum tempore quo dignissimos eveniet. Esse
                voluptates minima dolorem possimus temporibus nihil laborum
                animi, repellat exercitationem vitae deserunt officiis
                consectetur assumenda ea fugit deleniti qui, minus fuga a
                accusamus. Consectetur, temporibus? Illum tenetur amet
                doloremque! Sint odit excepturi aut, dicta ipsum odio iste totam
                consequatur et fuga aliquid, facilis animi corrupti consequuntur
                enim. Libero nobis dolore porro aliquam, veniam accusamus minima
                minus dolorem hic nemo! Placeat vero, voluptate possimus autem
                atque animi aperiam ipsum libero eum. Laboriosam provident sunt
                amet praesentium non iste quam ex, deleniti voluptatum commodi
                obcaecati temporibus repudiandae debitis iure doloremque!
                Magnam! Sunt odio ipsam doloremque rerum est officiis
                exercitationem nisi quisquam ipsa tempore facilis eos omnis
                autem voluptates corporis, ea assumenda possimus at vitae!
                Tempora error autem unde libero sequi! Obcaecati. Magnam tenetur
                minus non quis atque beatae eaque soluta, provident ducimus
                maiores dolorem corrupti reprehenderit facilis iusto adipisci
                deleniti consequatur blanditiis sunt qui quod vitae. Numquam
                consequuntur explicabo harum voluptatibus. Esse in error
                officiis aliquid sequi fuga nostrum harum facere sapiente
                reiciendis beatae, voluptate molestias amet eum sint perferendis
                id saepe provident mollitia quo cumque vitae, non dolorum.
                Dolorem, perferendis?
            </div>
        </>
    )
}

export default Home
